---
name: CI

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "repository to build"
        required: true
      ref:
        description: "branch, tag or SHA to checkout"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: login to registry
        run: >
          echo "${{ secrets.REGISTRY_PASSWORD }}"
          docker login "${{ secrets.REGISTRY_URL }}"
          -u "${{ secrets.REGISTRY_USERNAME }}"
          --password-stdin

      - name: checkout repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: use python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install
        run: |
          pip install black

      - name: lint
        run: |
          black *.py --check

      - name: build image
        run: |
          make docker
