---
name: CI

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "repository to build"
        required: true
      ref:
        description: "branch, tag or SHA to checkout"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: build image
        run: |
          make docker

      - name: push image
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login "${{ secrets.REGISTRY_URL }}" -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
          make docker_push
          docker logout "${{ secrets.REGISTRY_URL }}"
